### ISSUE TITLE
Error in sort_link

### ISSUE THREAD

**Issue by apohllo** [kaspernj/simple_form_ransack#17]
With the following code in view:
```
.scroll-panel-body
  = simple_search_form_for @query, @query_params do |f|
    = f.input :status_start, collection: Review::STATUS_MAPPING.keys, include_blank: true
    = f.submit "Filtruj", class: %w{btn btn-default btn-sm}
/ cut
        %th 
          = sort_link(@query, :deadline, "Deadline")
```
and in controller:
```ruby

  def index
    @query_params = params[:q] || {}
    @query = Review.ransack(@query_params)
    @query.sorts = ['deadline asc'] if @query.sorts.empty?
    @reviews = @query.result(distinct: true)
  end
```
After second click on a `sort_link` I get an error with following query params:
```ruby
{"q"=>{"builder"=>"SimpleForm::FormBuilder",
 "html"=>{"authenticity_token"=>"",
 "class"=>["simple_form",
 "new_review"],
 "id"=>"new_review",
 "method"=>"get",
 "multipart"=>"",
 "novalidate"=>"true"},
 "s"=>"deadline asc",
 "url"=>"/reviews?q%5Bs%5D=deadline+desc"}}
```
I am not 100% sure it's `simple_form_ransack` issue, but I guess so, since when I disable the form, everything works as expected. 

Can you please look into that?

**Comment by kaspernj** [comment]
Which version are you using? If you are using the latest, then you shouldn't supply `@query_params` any more.

So you would have to change your search form to:

```haml
= simple_search_form_for @query do |f|
```

Instead of:
```haml
= simple_search_form_for @query, @query_params do |f|
```

**Comment by apohllo** [comment]
Thanks, this solves this issue!





---- On Wt, 26 sty 2016 16:54:48 +0100 Kasper Johansen &lt;notifications@github.com&gt;wrote ---- 




Which version are you using? If you are using the latest, then you shouldn't supply @query_params any more.

So you would have to change your search form to:

= simple_search_form_for @query do |f|

Instead of:

= simple_search_form_for @query, @query_params do |f|

**Comment by kaspernj** [comment]
Great :-)
